### ISSUE TITLE
Beta release tracking issue

### ISSUE THREAD

**Issue by castrojo** [ublue-os/main#145]
Quick release checklist: 

- [x] Update latest tags to F38
- [x] Update ISO generator to source from `release` instead of `development` 
- [x] Beta announcement blog post
