### ISSUE TITLE
Tracker: New Universal Blue Installer

### ISSUE THREAD

**Issue by noelmiller** [ublue-os/main#468]
# Spec Document
https://hackmd.io/sNczIQz-SKau6oKUS6187Q?view

# Purpose
The current install method is either using the current ISO which is unreliable due to connectivity requirements or rebasing from the stock Silverblue project. This makes it difficult for new users of the project to try Universal Blue or current users to have a simpler method of installation. 

# Proposed Solution

Utilize upstream: https://github.com/JasonN3/container-installer
Our Fork: https://github.com/ublue-os/isogenerator

We are no longer going to attempt to use https://github.com/osbuild/bootc-image-builder

We may revisit it in the future if it provides features for modifying the kickstart file that is deployed by default with it and Fedora Atomic Desktops ship with bootc by default.

# Current Blockers for MVP

- [x] Finish github action to generate ISOs
  - https://github.com/ublue-os/build-action
  - Current work being done here: https://github.com/JasonN3/build-action/pull/1
- [x] Cleanup existing fork of container-installer and document how it works
  - https://github.com/ublue-os/isogenerator/pull/7

# Nice to Haves

- [ ] Live ISO Images for Bazzite and Bluefin
  - https://github.com/ublue-os/isogenerator/issues/8
- [ ] Install flatpaks as part of image creation
  - https://github.com/ublue-os/isogenerator/issues/9
- [ ] Use new Anaconda Web UI
  - https://github.com/ublue-os/isogenerator/issues/10

# Discussion
Discussion Thread is being archived here: https://www.answeroverflow.com/m/1192504002252914791

**Comment by castrojo** [comment]
Current isogenerator: https://github.com/ublue-os/isogenerator

I don't think we'd need a new action we'd just adapt this one? Unless we want to have a standalone osbuild action that would be useful to the osbuild project, because if we're going to do it it'd be awesome for everyone who uses osbuild after us can reuse a generic action.

**Comment by EyeCantCU** [comment]
I think having a generic osbuild action is the way to go

**Comment by castrojo** [comment]
I've closed most of the old iso tagged issues with instructions to the new installation page.

**Comment by noelmiller** [comment]
All issues in this tracker issue are open on isogenerator repo. There is no reason to keep this tracker open. Closing
