### ISSUE TITLE
F40 Release Checklist

### ISSUE THREAD

**Issue by bsherman** [ublue-os/main#529]
A list of tasks to complete for F40 release. Details can be discussed in comments.

- [x] add F40 builds to `akmods`
    - [x] disable kmod builds for negative17 sourced kmods (not yet supporting F40)
    - [x] enable kmod builds for negative17 sourced kmods when supported (see: https://github.com/ublue-os/akmods/issues/144)
    - [x] disable kmod builds which fail to compile on kernel 6.8
    - [x] enable kmod builds which fail to compile on kernel 6.8 when they work again (see: https://github.com/ublue-os/akmods/issues/144)
- [x] add F40 builds to `main` repo
    - ~~after F40 officially releases, switch upstream to quay.io/fedora images (in main and maybe akmods) (see: https://github.com/ublue-os/main/issues/78)~~ - pushed to F41
- [x] complete https://github.com/ublue-os/nvidia/issues/206
- [x] add F40 builds to `hwe` repo
- [x] add F40 builds to `bluefin` repo
- [x] add F40 builds to `bazzite` repo

Tagging and RPMfusion Cutover PRs:
- [x] akmods: https://github.com/ublue-os/akmods/pull/181
- [x] main: https://github.com/ublue-os/main/pull/563
- [x] hwe: https://github.com/ublue-os/hwe/pull/240
- [x] aurora/bluefin: https://github.com/ublue-os/bluefin/pull/1186
- [x] bazzite:

**Comment by FlyinPancake** [comment]
PR for `bazzite` Fedora 40 support <https://github.com/ublue-os/bazzite/pull/945>

**Comment by m2Giles** [comment]
PR for F40 bump in `bluefin/aurora`  https://github.com/ublue-os/bluefin/pull/1186

**Comment by gmankab** [comment]
can you please also update iso lmages to f40?

**Comment by bsherman** [comment]
> can you please also update iso lmages to f40?

Please file a request for update ISOs in the respective projects:
- https://github.com/ublue-os/bazzite
- https://github.com/ublue-os/bluefin

Universal Blue is not currently building ISOs for main or hwe images.

**Comment by bsherman** [comment]
This ticket was meant to be closed when moved to "Done" last week.

**Comment by gmankab** [comment]
> Universal Blue is not currently building ISOs for main or hwe images

but there are f39 iso files here https://archive.org/details/@ublueuploadtest

**Comment by bsherman** [comment]
> > Universal Blue is not currently building ISOs for main or hwe images
> 
> but there are f39 iso files here https://archive.org/details/@ublueuploadtest

I believe those are test products not produced or maintained by the Universal Blue team.

**Comment by gmankab** [comment]
this is very sad to hear

i thought it was official becouse on universal-blue.org there is a [direct usage instructions](https://universal-blue.discourse.group/docs?topic=868) link, and the instructions contains this archive.org link with outdated f39 iso images

are there any plans for official ublue iso images in future?

**Comment by bsherman** [comment]
> i thought it was official because there is a [direct usage instructions](https://universal-blue.discourse.group/docs?topic=868) link on universal-blue.org, and the instructions contains this archive.org link with outdated f39 iso images

Thanks for letting us know about this link. I've corrected it to avoid future confusion.
