### ISSUE TITLE
Discord Improvements

### ISSUE THREAD

**Issue by noelmiller** [ublue-os/main#574]
# Purpose 

There are improvements that should be made on the discord. All of these have been +1'ed by several members.

# Todos

- [ ] Create regularly scheduled game nights and hack nights.
- [ ] Remove tty voice channel
- [ ] Archive kinoite channel
- [ ] Change showcase to only allow threading
